### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#10909]
## Syntax
- [ ] `map{}` syntax
  - [ ] Introduce: `2021-08-01` (needs to be introduced when short struct init is removed)
  - [ ] Remove: `2021-09-01`
- [ ] `{}` short struct init
    - [ ] Remove: `2021-08-01`
- [ ] `automatic referencing/dereferencing`
- [ ] `casting to struct`
- [ ] `string errors` (only err.msg should be possible)
- [ ] `substr in str` (use `str.contains(substr)`)

## vlib
- [ ] `arrays.shuffle`
- [ ] `bitfield.cmp`
  - [ ] Remove: `2021-08-01`
- [ ] `builtin.is_atty`
- [ ] `string.tos_lit`
- [ ] `encoding.utf8.char_len`
- [ ] `hash.wyhash64`
- [ ] `io.make_reader`
  - [ ] Remove: `2021-08-01`
- [ ] `net.write_str`
- [ ] `net.unix.write_str`
- [ ] `net.websocket.write_str`
- [ ] `strconv.decimal_len_32`
- [ ] `strconv.decimal_len_64`
- [ ] `time.wait`
- [ ] `time.sleep_ms`
- [ ] `time.usleep`
- [ ] `vweb.set_cookie_old`
- [ ] `x.websocket.new_client`
- [ ] `x.websocket.write_str`
- [ ] `x.websocket.new_server`

Everyone can extend the list if something was found that is deprecated.

**Comment by danieldaeschle** [comment]
@yuyi98 Do you want to remove `map{}` syntax?

**Comment by depperm** [comment]
can some more details or links to discord be provided for some of these?
