### ISSUE TITLE
new v playground issues 

### ISSUE THREAD

**Issue by nedpals** [vlang/v#11255]
- [ ] https://github.com/vlang/v/issues/2677 - Outputs `Caught fatal signal 11`
- [ ] https://github.com/vlang/v/issues/2655 - Outputs `Time limit exceeded (wall clock)`
- [ ] https://github.com/vlang/v/issues/3033 - Outputs `Caught fatal signal 11`
- [ ] https://github.com/vlang/v/issues/3036 - Outputs `unfinished string literal`
- [ ] https://github.com/vlang/v/issues/5300 - invalid memory access
