### ISSUE TITLE
Fix all remaining issues with interfaces.

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#7002]
Tasks:
- [x] https://github.com/vlang/v/issues/73
- [x] https://github.com/vlang/v/issues/1091 - not related to V's interfaces
- [x] https://github.com/vlang/v/issues/1081 - "It is possible to mutate an immutable value through an interface"
- [x] https://github.com/vlang/v/issues/990
- [x] https://github.com/vlang/v/issues/354 - "Returning interface doesn't work"; needs more work.
- [x] https://github.com/vlang/v/issues/2377 - arrays of interfaces
- [x] https://github.com/vlang/v/issues/2706
- [x] https://github.com/vlang/v/issues/2709
- [x] https://github.com/vlang/v/issues/3714
- [x] https://github.com/vlang/v/issues/4577
- [x] https://github.com/vlang/v/issues/5138
- [x] https://github.com/vlang/v/issues/4721
- [x] https://github.com/vlang/v/issues/5171
- [x] https://github.com/vlang/v/issues/5184
- [x] https://github.com/vlang/v/issues/5246
- [x] https://github.com/vlang/v/issues/6871
- [x] https://github.com/vlang/v/issues/6714
- [x] https://github.com/vlang/v/issues/7039
- [x] https://github.com/vlang/v/issues/5267
- [x] https://github.com/vlang/v/issues/5291
- [x] https://github.com/vlang/v/issues/5310
- [x] https://github.com/vlang/v/issues/5328
- [x] https://github.com/vlang/v/issues/5534
- [x] https://github.com/vlang/v/issues/5535
- [x] https://github.com/vlang/v/issues/5536
- [x] https://github.com/vlang/v/issues/5538
- [x] https://github.com/vlang/v/issues/5539
- [x] https://github.com/vlang/v/issues/5540
- [x] https://github.com/vlang/v/issues/5790
- [x] https://github.com/vlang/v/issues/5867
- [x] https://github.com/vlang/v/issues/6125
- [x] https://github.com/vlang/v/issues/6235
- [x] https://github.com/vlang/v/issues/7123
- [x] https://github.com/vlang/v/issues/7813
- [ ] https://github.com/vlang/v/issues/8052
- [x] https://github.com/vlang/v/issues/8465
- [ ] https://github.com/vlang/v/issues/10980
- [x] https://github.com/vlang/v/issues/13296

**Comment by kahsa** [comment]
#7123 please

**Comment by kahsa** [comment]
#13414

**Comment by Hunam6** [comment]
added those

**Comment by medvednikov** [comment]
Just one issue remaining, this can be closed.
