### ISSUE TITLE
Native JSON support

### ISSUE THREAD

**Issue by nedpals** [vlang/v#7032]
This issue tracks the current progress of native JSON support that will replace the CJSON-based `json` module. Replaces #309.

### PR's
- [x] ~~Add `x/json2` (#6336)~~
- [x] ~~Add i64 and f32 support (#6586)~~
- [x] ~~Have `json2.decode` return `?T` (#6933)~~
- [ ] Encoder/decoder codegen

### Related Issues
Just a series of issues whose suggestions can be a good addition to the codegen.

- [x] Implement `omitifempty` (#6571, #6344)
- [x] Support for aliased types (#6225)
